name: Auto Vote

on:
  schedule:
    - cron: '*/3 * * * *'  # Runs every 31 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  vote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Chrome and ChromeDriver artifacts
        uses: actions/download-artifact@v3
        with:
          name: chrome-setup
          path: /usr/local/bin/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run the vote script
        run: |
          python click_button.py
